Traceback (most recent call last):
  File "dpicl-llama.py", line 210, in <module>
    tokenizer = AutoTokenizer.from_pretrained(model_id,
  File "/home/woodygan/.conda/envs/dpicl/lib/python3.8/site-packages/transformers/models/auto/tokenization_auto.py", line 834, in from_pretrained
    tokenizer_config = get_tokenizer_config(pretrained_model_name_or_path, **kwargs)
  File "/home/woodygan/.conda/envs/dpicl/lib/python3.8/site-packages/transformers/models/auto/tokenization_auto.py", line 666, in get_tokenizer_config
    resolved_config_file = cached_file(
  File "/home/woodygan/.conda/envs/dpicl/lib/python3.8/site-packages/transformers/utils/hub.py", line 402, in cached_file
    resolved_file = hf_hub_download(
  File "/home/woodygan/.conda/envs/dpicl/lib/python3.8/site-packages/huggingface_hub/utils/_deprecation.py", line 101, in inner_f
    return f(*args, **kwargs)
  File "/home/woodygan/.conda/envs/dpicl/lib/python3.8/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "/home/woodygan/.conda/envs/dpicl/lib/python3.8/site-packages/huggingface_hub/file_download.py", line 1240, in hf_hub_download
    return _hf_hub_download_to_cache_dir(
  File "/home/woodygan/.conda/envs/dpicl/lib/python3.8/site-packages/huggingface_hub/file_download.py", line 1357, in _hf_hub_download_to_cache_dir
    os.makedirs(os.path.dirname(blob_path), exist_ok=True)
  File "/home/woodygan/.conda/envs/dpicl/lib/python3.8/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/home/woodygan/.conda/envs/dpicl/lib/python3.8/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/home/woodygan/.conda/envs/dpicl/lib/python3.8/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/home/woodygan/.conda/envs/dpicl/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/data/james'
